## Global Historical Climatology Network Dataset
Variables are stored in both rows and columns
This dataset represents the daily weather records for a weather station (MX17004) in Mexico for five months in 2010.

In [16]:
import pandas as pd
weather = pd.read_csv("..\weather-raw.csv")
weather.shape

(22, 35)

In [13]:
weather.head(3)

,id,year,month,element,d1,d2,d3,d4,d5,d6,...,d22,d23,d24,d25,d26,d27,d28,d29,d30,d31
0,MX17004,2010,1,tmax,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.8,NaN
1,MX17004,2010,1,tmin,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.5,NaN
2,MX17004,2010,2,tmax,NaN,27.3,24.1,NaN,NaN,NaN,...,NaN,29.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
weather.tail(3)

,id,year,month,element,d1,d2,d3,d4,d5,d6,...,d22,d23,d24,d25,d26,d27,d28,d29,d30,d31
19,MX17004,2010,11,tmin,NaN,16.3,NaN,12.0,7.9,NaN,...,NaN,NaN,NaN,NaN,12.1,14.2,NaN,NaN,NaN,NaN
20,MX17004,2010,12,tmax,29.9,NaN,NaN,NaN,NaN,27.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,MX17004,2010,12,tmin,13.8,NaN,NaN,NaN,NaN,10.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
weather.fillna(0.0, inplace=True)
weather

,id,year,month,element,d1,d2,d3,d4,d5,d6,...,d22,d23,d24,d25,d26,d27,d28,d29,d30,d31
0,MX17004,2010,1,tmax,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,27.8,0.0
1,MX17004,2010,1,tmin,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14.5,0.0
2,MX17004,2010,2,tmax,0.0,27.3,24.1,0.0,0.0,0.0,...,0.0,29.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,MX17004,2010,2,tmin,0.0,14.4,14.4,0.0,0.0,0.0,...,0.0,10.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,MX17004,2010,3,tmax,0.0,0.0,0.0,0.0,32.1,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,MX17004,2010,3,tmin,0.0,0.0,0.0,0.0,14.2,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,MX17004,2010,4,tmax,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,36.3,0.0,0.0,0.0,0.0
7,MX17004,2010,4,tmin,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,16.7,0.0,0.0,0.0,0.0
8,MX17004,2010,5,tmax,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,33.2,0.0,0.0,0.0,0.0
9,MX17004,2010,5,tmin,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,18.2,0.0,0.0,0.0,0.0
10,MX17004,2010,6,tmax,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,30.1,0.0,0.0
11,MX17004,2010,6,tmin,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,18.0,0.0,0.0
12,MX17004,2010,7,tmax,0.0,0.0,28.6,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,MX17004,2010,7,tmin,0.0,0.0,17.5,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,MX17004,2010,8,tmax,0.0,0.0,0.0,0.0,29.6,0.0,...,0.0,26.4,0.0,29.7,0.0,0.0,0.0,28.0,0.0,25.4
15,MX17004,2010,8,tmin,0.0,0.0,0.0,0.0,15.8,0.0,...,0.0,15.0,0.0,15.6,0.0,0.0,0.0,15.3,0.0,15.4
16,MX17004,2010,10,tmax,0.0,0.0,0.0,0.0,27.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,31.2,0.0,0.0,0.0
17,MX17004,2010,10,tmin,0.0,0.0,0.0,0.0,14.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,15.0,0.0,0.0,0.0
18,MX17004,2010,11,tmax,0.0,31.3,0.0,27.2,26.3,0.0,...,0.0,0.0,0.0,0.0,28.1,27.7,0.0,0.0,0.0,0.0
19,MX17004,2010,11,tmin,0.0,16.3,0.0,12.0,7.9,0.0,...,0.0,0.0,0.0,0.0,12.1,14.2,0.0,0.0,0.0,0.0
20,MX17004,2010,12,tmax,29.9,0.0,0.0,0.0,0.0,27.8,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,MX17004,2010,12,tmin,13.8,0.0,0.0,0.0,0.0,10.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0